version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: "postgres-container"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: nanodata-desafio

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: ./nginx/.
    ports:
      - "80:80"
  
  api:
    depends_on:
      - db
    build: ./api/.
    restart: always

  client:
    depends_on:
      - api
    build: ./frontend/.
    restart: always


